### ISSUE TITLE
Atualizar Front Manter área de Interesse

### ISSUE THREAD

**Issue by Ikaruzdelta** [marcosdosea/eventos#101]

**Comment by Ikaruzdelta** [comment]
- Botão tem que ser padronizado, por exemplo: "Criar área de Interesse"
- O botão tem que ser abaixo da tabela.
- Botão tem que ser Large
- Botões na pagina de cadastro não estão alinhados corretamente.
- Colocar o modal na parte de excluir
- Tabela com o tamanho padrão

**Comment by ValdirMS** [comment]
Deverá esperar validação de protótipo para confirmar possíveis mudanças
