### ISSUE TITLE
Atualizações do Banco

### ISSUE THREAD

**Issue by ValdirMS** [marcosdosea/eventos#107]
Adicionar auto incremento para Id de TipoEvento e TipoInscricao
Retirar valorInscrição de Evento e Subevento
datafim de TipoInscricao deverá ser dataFim
Adicionar campo "Nome" a TipoInscricao

**Comment by marcosdosea** [comment]
Alterações realizadas. Exceto a remoção do valor para facilitar a listagem dos eventos.
