### ISSUE TITLE
Desenvolvimento do design system

### ISSUE THREAD

**Issue by Ikaruzdelta** [marcosdosea/eventos#6]

**Comment by Ikaruzdelta** [comment]
O Design System do projeto foi criado para garantir consistência visual e eficiência no desenvolvimento das interfaces. O Design System inclui uma série de componentes reutilizáveis, como botões e campos de entrada.

Além dos componentes, o guia de estilo detalha as cores utilizadas no projeto, incluindo os códigos hexadecimais para as cores primárias, secundárias, de fundo e de texto, além da tipografia padrão adotada, que utiliza a fonte Inter. Esta abordagem foi desenvolvida para não apenas padronizar a aparência das interfaces, mas também facilitar a manutenção e escalabilidade do projeto.

Segue o link para visualização do Design System: https://www.figma.com/design/YXrMAV9sD9hAosV8B8pJzo/BoraLa?node-id=12-2&t=c7oVImpcf8eNVGDy-1

**Comment by Nadianne** [comment]
Design system desenvolvido de forma consistente auxilando o projeto a ter padronização e fluidez nos processos.
